### ISSUE TITLE
MFA token not optional

### ISSUE THREAD

**Issue by jfexyz** [jbuck/assume-aws-role#3]
Despite the readme (`It's optional but highly recommended that you use a MFA device.`), it appears this cannot be used without MFA tokens.

**Comment by jfexyz** [comment]
Nevermind, that's my bad. It wasn't clear that you could leave off the MFA/user account when adding a role.

**Comment by jbuck** [comment]
This sounds like an example I should add to the README

**Comment by jbuck** [comment]
Okay, added to the README in assume-aws-role add sandbox \
  "arn:aws:iam::123456789012:role/Administrator"

Thanks for filing this issue!
