### ISSUE TITLE
Allow configuring the PS1 prompt

### ISSUE THREAD

**Issue by jfexyz** [jbuck/assume-aws-role#4]
Right now, it's forcibly overwritten, but there should probably be a way for the user to specify the format.

**Comment by jfexyz** [comment]
If this isn't ideal, maybe it should be up to the end user to implement their own prompt. Exposing the active alias via an environment variable would be helpful here.

**Comment by jbuck** [comment]
I did some reading on PS1 configuration, and it looks like you can't using environment variables inside the PS1 prompt. Does that sound right to you?

Perhaps the best option would be to allow users to set a PS1 string inside the config file. I should probably refactor how the configuration file is saved... it's not very extensible right now.

**Comment by jfexyz** [comment]
I'm not sure what you mean by not being able to use environment variables in PS1. What are you trying to do?

This change: 

``` js
modEnv.PS1 = modEnv.ASSUME_AWS_ROLE_PS1 || "(assume-aws-role " + command + ")$ ";
```

Works for me with: `ASSUME_AWS_ROLE_PS1="(myprompt)$ " assume-aws-role <role>`

Happy to open a PR if this direction works for you...

**Comment by jfexyz** [comment]
I've also got this working in a wrapper script that I use to call `assume-aws-role`, so you can use vars inside a PS1 var:

``` shell
#!/bin/bash

export AWS_ACCOUNT=ops-dev
export AWS_PROFILE=ops
export AWS_DEFAULT_REGION=`aws configure get region`
export AWS_REGION=$AWS_DEFAULT_REGION

ASSUME_AWS_ROLE_PS1="(aws: $AWS_ACCOUNT)$ " assume-aws-role $AWS_ACCOUNT
```

**Comment by fpavageau** [comment]
I'd rather add the role to the environment (e.g. as `ASSUME_AWS_ROLE`), so I can integrate it to my default `PS1`. I'll just open a PR with the simple change, you can do .

IMO, it would supersede the currently open #11 PR by allowing the user to customize the prompt as she sees fit, whether it's including the current directory, colors, the status of the last command, etc.
